name: urbanfootprint
description: A Sneakers App - Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  custom_navigation_bar: ^0.8.2
  supercharged: ^2.1.1
  simple_animations: ^4.2.0
  provider: ^6.1.2
  chewie: ^1.8.1
  video_player: ^2.8.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  http: ^1.2.1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  mpesa_flutter_plugin: ^1.6.1
  carousel_slider: ^4.2.1
  form_field_validator: ^1.1.0
  shared_preferences: ^2.2.3
  intl: ^0.17.0
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-Regular.ttf
        - asset: assets/fonts/Alegreya-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
