// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoLwTB7KHv76q5G4FjngR_JA2aZJybb4',
    appId: '1:831178674259:web:965a6186dc6d5b6e1336a6',
    messagingSenderId: '831178674259',
    projectId: 'urbanfootprint-a3611',
    authDomain: 'urbanfootprint-a3611.firebaseapp.com',
    storageBucket: 'urbanfootprint-a3611.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnraaQNuE998lXuxD6fBtRmvy4yBmvxXk',
    appId: '1:831178674259:android:e739cdd1fb527e721336a6',
    messagingSenderId: '831178674259',
    projectId: 'urbanfootprint-a3611',
    storageBucket: 'urbanfootprint-a3611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbGHolVbMzIXPozsyjD82J-3mc_64D_ts',
    appId: '1:831178674259:ios:1a1c5b59313805191336a6',
    messagingSenderId: '831178674259',
    projectId: 'urbanfootprint-a3611',
    storageBucket: 'urbanfootprint-a3611.appspot.com',
    iosBundleId: 'com.example.urbanfootprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbGHolVbMzIXPozsyjD82J-3mc_64D_ts',
    appId: '1:831178674259:ios:a892179d3933fec31336a6',
    messagingSenderId: '831178674259',
    projectId: 'urbanfootprint-a3611',
    storageBucket: 'urbanfootprint-a3611.appspot.com',
    iosBundleId: 'com.example.urbanfootprint.RunnerTests',
  );
}
